name: ridesharing_app
description: Paylaşımlı Yolculuk Uygulaması - İnsan, hayvan, yük ve gıda taşımacılığı
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.6.1
  
  # Localization
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  
  # Navigation
  go_router: ^14.0.0
  
  # Network
  dio: ^5.4.0

  # Push Notifications
  firebase_core: ^3.9.0
  firebase_messaging: ^15.2.0
  
  # Local Storage
  shared_preferences: ^2.5.0
  flutter_secure_storage: ^9.2.4
  
  # QR Code
  qr_flutter: ^4.1.0
  
  # UI & Animations
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  flutter_animate: ^4.5.2      # Smooth animations
  flutter_svg: ^2.0.17         # SVG icons
  lottie: ^3.3.1               # Lottie animations

  # Maps & Location (OpenStreetMap)
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  http: ^1.2.0 # For OSRM routing
  
  # Cache
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.1

  # Camera & Gallery
  image_picker: ^1.0.7

  # Utils
  uuid: ^4.5.0
  file_selector: ^1.0.3
  camera: ^0.10.5+9
  socket_io_client: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/ID-Verification-1.jpg

